server.port: 8080
spring:
  application.name: manager
  datasource:
    driverClassName: org.h2.Driver
    password: 123
    url: jdbc:h2:file:./src/main/resources/database/manager-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
  h2:
    console:
      enabled: true
      # Permite acesso remoto
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Alterar para create-drop em caso de mudanca do schema
      ddl-auto: update
    show-sql: true